FROM node:16-alpine
WORKDIR '/app'
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
COPY ./package.json ./
RUN npm config set registry http://registry.npmjs.org/
RUN npm config set strict-ssl=false
RUN npm install
COPY . .
CMD ["npm", "run", "start"]

